[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 115200
board_build.partitions = huge_app.csv

lib_deps =
    adafruit/Adafruit_VL53L0X @ ^1.2.4
    madhephaestus/ESP32Servo @ ^3.0.5
    hideakitai/MPU9250 @ ^0.4.8
    bblanchon/ArduinoJson @ ^7.0.4
    arduino-libraries/Madgwick @ ^1.2.0
